### PR TITLE
Allow multiple handlers from a single ChangeStream

### PR DESCRIPTION
**Pull request by FreakTheMighty**
This appears to resolve an issue I was having related to #13. I haven't been able to run the test, I'm seeing:

```
ReferenceError: Can't find variable: angular
```

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by davidcheung** [comment]
@slnode ok to test

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by slnode** [comment]
Can one of the admins verify this patch?

**Comment by davidcheung** [comment]
@FreakTheMighty sorry for the late reply, would you be able to see if this is still an issue and  rebase on top of the current master?

**Comment by dhmlau** [comment]
Closing as abandoned.

**Pull request closed without merging**
