### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by viki53**
Fixed typo

### CODE REVIEW

**Comment by slnode** [comment]
Can one of the admins verify this patch? To accept patch and trigger a build add comment ".*ok\W+to\W+test.*"

**Comment by superkhau** [comment]
Please sign the CLA at https://cla.strongloop.com/agreements/strongloop/angular-live-set

**Comment by superkhau** [comment]
@viki53 Ping.

**Comment by 0candy** [comment]
Should be fixed by https://github.com/strongloop/angular-live-set/pull/20

**Pull request closed without merging**
